import { Destination } from "./types";

export const destinations: Destination[] = [
  {
    id: "dominikai-koztarsasag",
    name: "Dominikai Köztársaság",
    description:
      "Karibi paradicsom fehér homokos strandokkal és pálmafákkal. Az all-inclusive resortok világszínvonalúak, és az ár-érték arányt tekintve az egyik legjobb karibi célállomás.",
    highlights: [
      "Fehér homokos strandok",
      "All-inclusive resortok",
      "Vízi sportok",
      "Karibi kultúra",
    ],
    pros: [
      "A Karib-tenger legjobb ár-érték arányú célállomása",
      "Hatalmas, pálmafás strandok — nem kell helyért harcolni",
      "All-inclusive szállások tényleg mindent tartalmaznak",
      "Snorkelezés, búvárkodás, katamaránozás helyben",
    ],
    bestFor:
      "Aki karibi hangulatot akar all-inclusive kényelemmel, de nem akar annyit fizetni, mint a Maldívon",
    programs: [
      "🏖️ Punta Cana strandok és vízi sportok",
      "🤿 Snorkelezés a korallzátonyoknál",
      "🚤 Katamarán túra Saona-szigetre",
      "💃 Merengue est és rum kóstoló",
      "🏇 Lovaglás a tengerparton",
      "🌿 Ökotúra a dzsungelben",
    ],
    comparison:
      "Olcsóbb karibi élmény, mint Maldív vagy Seychelles, de távolabb van, mint a görög szigetek. Az all-inclusive hasonlóan jó, mint Törökországban, de egzotikusabb.",
    travelTime: "~12 óra (1 átszállással)",
    costCategory: "€€€",
    imageUrls: [
      "https://images.unsplash.com/photo-1613694933102-74d2e29e159f?w=800&q=80&fit=crop",
      "https://images.unsplash.com/photo-1602608101172-fcc366320a33?w=800&q=80&fit=crop",
      "https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800&q=80&fit=crop",
      "https://images.unsplash.com/photo-1561214115-f2f134cc4912?w=800&q=80&fit=crop",
      "https://images.unsplash.com/photo-1580541631950-7282082b53ce?w=800&q=80&fit=crop",
    ],
    imageAlts: [
      "Dominikai strand pálmafákkal",
      "Karibi tengerpart",
      "All-inclusive resort medencével",
      "Türkizkék víz és snorkelező",
      "Karibi naplemente",
    ],
    fallbackGradient: "from-cyan-400 to-blue-600",
    fallbackEmoji: "🌴",
  },
  {
    id: "dubai",
    name: "Dubai",
    description:
      "A luxus és a modernség városa. A világ legmagasabb épülete, mesterséges szigetek, sivatagi szafari és világszínvonalú bevásárlási lehetőségek.",
    highlights: [
      "Burj Khalifa",
      "Sivatagi szafari",
      "Luxus shopping",
      "Víziparkok",
    ],
    pros: [
      "Garantált napsütés és 5 csillagos szolgáltatás",
      "Egyedülálló élmények: sivatag + város + tenger egy helyen",
      "Közvetlen járat Budapestről, csak 6 óra",
      "Biztonságos, tiszta, családbarát város",
    ],
    bestFor:
      "Aki luxust, modern városélményt és sivatagi kalandot akar egyszerre — és nem baj, ha drágább",
    programs: [
      "🏙️ Burj Khalifa kilátó (148. emelet!)",
      "🏜️ Sivatagi szafari dzsippel + vacsora a csillagok alatt",
      "🎢 Aquaventure vízipark (a világ egyik legnagyobb)",
      "🛍️ Dubai Mall — jégpálya, akváriummal!",
      "🚤 Yacht túra a Palm Jumeirah körül",
      "🎿 Ski Dubai — síelés a sivatagban",
      "🌅 Abu Dhabi napi kirándulás",
    ],
    comparison:
      "Drágább, mint Törökország vagy a görög szigetek, de közelebb van, mint Amerika. A városélmény egyedülálló — sehol máshol nincs ilyen. Strandélményben viszont a görög szigetek jobbak.",
    travelTime: "~6 óra (közvetlen járat)",
    costCategory: "€€€€",
    imageUrls: [
      "https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=800&q=80&fit=crop",
      "https://images.unsplash.com/photo-1518684079-3c830dcef090?w=800&q=80&fit=crop",
      "https://images.unsplash.com/photo-1651063820152-d3e7a27b4d2b?w=800&q=80&fit=crop",
      "https://images.unsplash.com/photo-1580674285054-bed31e145f59?w=800&q=80&fit=crop",
      "https://images.unsplash.com/photo-1706464962626-b537c2f7e19b?w=800&q=80&fit=crop",
      "https://images.unsplash.com/photo-1513415564515-763d91423bdd?w=800&q=80&fit=crop",
    ],
    imageAlts: [
      "Burj Khalifa éjszaka",
      "Dubai Marina felhőkarcolók",
      "Burj Khalifa nappal",
      "Palm Jumeirah légi fotó",
      "Dubai Marina éjjeli panoráma",
      "Hagyományos arab souk piac",
    ],
    fallbackGradient: "from-amber-400 to-orange-600",
    fallbackEmoji: "🏙️",
  },
  {
    id: "thaifold",
    name: "Thaiföld",
    description:
      "Egész életedre szóló élmény: buddhista templomok, trópusi tengerpartok, világszínvonalú thai konyha és hihetetlenül barát emberek.",
    highlights: [
      "Egzotikus strandok",
      "Thai konyha",
      "Templomok",
      "Olcsó luxus",
    ],
    pros: [
      "Hihetetlen ár-érték arány — a pénzedért 3x annyit kapsz",
      "A világ legjobb street food-ja és étteremkultúrája",
      "Strandok, dzsungel, templomok — végtelen változatosság",
      "Thai masszázs napi szinten, fillérekért",
    ],
    bestFor:
      "Aki egzotikus kalandot akar olcsón, és szereti a jó kaját. Kulturális élmény + strand egyben.",
    programs: [
      "🏝️ Phi Phi-szigetek hajókirándulás",
      "🛕 Bangkok templomok (Wat Pho, Wat Arun)",
      "🐘 Elefánt menedékhely látogatás",
      "🍜 Street food túra Bangkokban",
      "🧘 Thai masszázs és spa",
      "🤿 Snorkelezés Koh Tao-nál",
      "🛶 Kano túra a mangrove erdőben",
      "🌙 Éjszakai piac és tűzzsonglőrök",
    ],
    comparison:
      "Messze a legjobb ár-érték arány az egzotikus célállomások közül. Távolabb van, mint a görög szigetek, de sokkal olcsóbb, mint Maldív vagy Seychelles, és sokkal több programot kínál.",
    travelTime: "~11-12 óra (1 átszállással)",
    costCategory: "€€",
    imageUrls: [
      "https://images.unsplash.com/photo-1504214208698-ea1916a2195a?w=800&q=80&fit=crop",
      "https://images.unsplash.com/photo-1528181304800-259b08848526?w=800&q=80&fit=crop",
      "https://images.unsplash.com/photo-1552465011-b4e21bf6e79a?w=800&q=80&fit=crop",
      "https://images.unsplash.com/photo-1537953773345-d172ccf13cf1?w=800&q=80&fit=crop",
      "https://images.unsplash.com/photo-1563492065599-3520f775eeed?w=800&q=80&fit=crop",
      "https://images.unsplash.com/photo-1506665531195-3566af2b4dfa?w=800&q=80&fit=crop",
    ],
    imageAlts: [
      "Phi Phi szigetek trópusi víz",
      "Bangkok Wat Arun templom",
      "Thai street food piac",
      "Long-tail csónak a tengerparton",
      "Tuk-tuk Bangkokban",
      "Thai masszázs spa",
    ],
    fallbackGradient: "from-emerald-400 to-teal-600",
    fallbackEmoji: "🛕",
  },
  {
    id: "amerika-las-vegas-la",
    name: "Amerika (Las Vegas – Los Angeles)",
    description:
      "Két ikon, egy utazás! Las Vegas kaszinói és show-i, majd Los Angeles: Hollywood, Santa Monica és a Csendes-óceáni part.",
    highlights: [
      "Las Vegas Strip",
      "Grand Canyon",
      "Hollywood",
      "Road trip",
    ],
    pros: [
      "Két világváros egy utazásban — teljesen más élmény mindkettő",
      "Grand Canyon az egyik legcsodálatosabb természeti látnivaló a Földön",
      "Igazi amerikai élmény: hamburger, motel, highway",
      "Show-k, kaszinók, Beverly Hills — egyedülálló hangulat",
    ],
    bestFor:
      "Aki road trip kalandot, amerikai kultúrát és városélményt akar. Nem klasszikus strand-nyaralás!",
    programs: [
      "🎰 Las Vegas Strip séta és kaszinó-este",
      "🎪 Cirque du Soleil vagy más world-class show",
      "🏜️ Grand Canyon napi kirándulás (helikopterrel is!)",
      "🎬 Hollywood Walk of Fame és stúdiótúra",
      "🏖️ Santa Monica Pier és Venice Beach",
      "🛍️ Outlet shopping (50-70% kedvezmények!)",
      "🚗 Road trip a Mojave-sivatagon át",
      "🌉 Beverly Hills és Rodeo Drive séta",
    ],
    comparison:
      "Teljesen más, mint bármelyik másik opció — ez nem strand-nyaralás, hanem kaland. A leghosszabb utazás és a legdrágább, de cserébe egyedülálló élmény, amit máshol nem kapsz.",
    travelTime: "~13-14 óra (1 átszállással)",
    costCategory: "€€€€",
    imageUrls: [
      "https://images.unsplash.com/photo-1605833556294-ea5c7a74f57d?w=800&q=80&fit=crop",
      "https://images.unsplash.com/photo-1506197603052-3cc9c3a201bd?w=800&q=80&fit=crop",
      "https://images.unsplash.com/photo-1542224566-6e85f2e6772f?w=800&q=80&fit=crop",
      "https://images.unsplash.com/photo-1534430480872-3498386e7856?w=800&q=80&fit=crop",
      "https://images.unsplash.com/photo-1580655653885-65763b2597d0?w=800&q=80&fit=crop",
      "https://images.unsplash.com/photo-1501594907352-04cda38ebc29?w=800&q=80&fit=crop",
    ],
    imageAlts: [
      "Las Vegas Strip éjszaka fényekkel",
      "Grand Canyon naplemente",
      "Hollywood felirat a dombon",
      "Santa Monica Pier",
      "Beverly Hills pálmafasor",
      "Route 66 sivatagban",
    ],
    fallbackGradient: "from-purple-500 to-pink-600",
    fallbackEmoji: "🎰",
  },
  {
    id: "seychelles",
    name: "Seychelles",
    description:
      "A Földi Paradicsom. Gránit sziklák közötti strandok, kristálytiszta víz és érintetlen természet. A világ legszebb strandjai itt vannak.",
    highlights: [
      "Világ legszebb strandjai",
      "Gránit sziklák",
      "Érintetlen természet",
      "Exkluzív élmény",
    ],
    pros: [
      "Az Anse Source d'Argent világ TOP 3 strandja",
      "Érintetlen, vadregényes természet — nem tömeges turizmus",
      "Egyedülálló gránit sziklás tájkép, ami sehol máshol nincs",
      "Teknősök, trópusi madarak, korallzátonyok",
    ],
    bestFor:
      "Aki a világ legszebb strandjait akarja látni, és nem baj, ha prémium áron. Romantikus + természetközeli.",
    programs: [
      "🏖️ Anse Source d'Argent — a legikonikusabb strand",
      "🐢 Óriás teknős rezervátum (Aldabra teknősök!)",
      "🤿 Snorkelezés és búvárkodás korallzátonyoknál",
      "🥾 Morne Seychellois Nemzeti Park túra",
      "🚤 Szigethopping csónakkal",
      "🌅 Naplemente a gránit sziklák között",
    ],
    comparison:
      "A Maldívokhoz hasonlóan luxus kategória, de itt a strandok sokkal változatosabbak (gránit sziklák!). Drágább, mint bármelyik európai opció, de az élmény is más liga.",
    travelTime: "~12-13 óra (1 átszállással)",
    costCategory: "€€€€",
    imageUrls: [
      "https://images.unsplash.com/photo-1589979481223-deb893043163?w=800&q=80&fit=crop",
      "https://images.unsplash.com/photo-1609137144813-7d9921338f24?w=800&q=80&fit=crop",
      "https://images.unsplash.com/photo-1551244072-5d12893278ab?w=800&q=80&fit=crop",
      "https://images.unsplash.com/photo-1590523741831-ab7e8b8f9c7f?w=800&q=80&fit=crop",
      "https://images.unsplash.com/photo-1583417319070-4a69db38a482?w=800&q=80&fit=crop",
    ],
    imageAlts: [
      "Anse Source d'Argent gránit sziklái",
      "Teknős a parton",
      "Kristálytiszta víz korallzátonnyal",
      "Trópusi növényzet",
      "Pálmafák és türkiz tenger",
    ],
    fallbackGradient: "from-teal-300 to-cyan-600",
    fallbackEmoji: "🪨",
  },
  {
    id: "maldiv",
    name: "Maldív-szigetek",
    description:
      "Víz feletti bungalók, végtelen türkizkék lagúna és teljes nyugalom. A luxus tengerparti pihenések csúcsa.",
    highlights: [
      "Víz feletti bungalók",
      "Türkiz lagúna",
      "Búvárkodás",
      "Totális luxus",
    ],
    pros: [
      "A víz feletti bungaló egyike az élet nagy élményeinek",
      "Kristálytiszta, sekély lagúnák — gyerekeknek is biztonságos",
      "Világszínvonalú búvár- és snorkelhelyek (manta ráják!)",
      "Teljes kikapcsolódás — semmi stressz, semmi tömeg",
    ],
    bestFor:
      "Aki teljes luxust és nyugalmat akar a világ legszebb vizein. A tökéletes 'semmittevés' nyaralás.",
    programs: [
      "🏠 Víz feletti bungaló élmény (üvegpadló!)",
      "🤿 Snorkelezés manta rájákkal és tengeri teknősökkel",
      "🐠 Búvárkodás korallkertekben",
      "🚤 Delfin-figyelő naplemente túra",
      "🎣 Mélytengeri horgászat",
      "🍽️ Víz alatti étterem (Ithaa)",
      "💆 Spa kezelés az óceán felett",
    ],
    comparison:
      "A legdrágább opció, de a víz feletti bungaló élményt nem kapod meg máshol. Kevesebb program, mint Thaiföldön, de a nyugalom és luxus páratlan. Seychelles-hez képest több a vízi élmény, kevesebb a természetjárás.",
    travelTime: "~11-12 óra (1 átszállással)",
    costCategory: "€€€€",
    imageUrls: [
      "https://images.unsplash.com/photo-1514282401047-d79a71a590e8?w=800&q=80&fit=crop",
      "https://images.unsplash.com/photo-1573843981267-be1999ff37cd?w=800&q=80&fit=crop",
      "https://images.unsplash.com/photo-1589182337358-2cb63099350c?w=800&q=80&fit=crop",
      "https://images.unsplash.com/photo-1506929562872-bb421503ef21?w=800&q=80&fit=crop",
      "https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800&q=80&fit=crop",
      "https://images.unsplash.com/photo-1573843981267-be1999ff37cd?w=800&q=80&fit=crop",
    ],
    imageAlts: [
      "Víz feletti bungalók sorban",
      "Bungaló belső üvegpadlóval",
      "Búvár manta rájával",
      "Végtelen türkiz lagúna",
      "Romantikus vacsora a víz felett",
      "Naplemente a bungalóknál",
    ],
    fallbackGradient: "from-blue-300 to-indigo-500",
    fallbackEmoji: "🏝️",
  },
  {
    id: "mallorca",
    name: "Mallorca",
    description:
      "Spanyol sziget a Földközi-tengeren: gyönyörű öblök, finom tapas, és a családi nyaralás klasszikusa.",
    highlights: [
      "Gyönyörű öblök",
      "Spanyol konyha",
      "Családbarát",
      "Rövid repülőút",
    ],
    pros: [
      "3 óra alatt ott vagy — a legrövidebb utazás az egzotikusabb célok közül",
      "Gyönyörű türkiz öblök (Cala d'Or, Cala Millor, Cala Mondragó)",
      "Palma de Mallorca pezsgő óvárosa, piacok, éttermek",
      "Autóval körbejárható, rugalmas programok",
    ],
    bestFor:
      "Aki szép strandokat és spanyol hangulatot akar rövid repülőúttal, és fontos a rugalmasság.",
    programs: [
      "🏖️ Cala-hopping: Cala d'Or, Mondragó, Varques",
      "🏰 Palma de Mallorca óváros és katedrális",
      "🚗 Autós körtúra a Serra de Tramuntana hegységben",
      "🍷 Borkóstoló helyi pincészetben",
      "🚴 Kerékpár túra (a profik is itt edznek!)",
      "🌊 Csónaktúra a Drach-barlangokhoz",
      "🍤 Tapas-est Palma óvárosában",
    ],
    comparison:
      "A görög szigetekhez hasonló távolság és árkategória, de spanyol hangulat görög helyett. A strand-minőségben a görög szigetek nyernek, de Mallorca rugalmasabb (autóval járható, több a program).",
    travelTime: "~2.5-3 óra (közvetlen járat)",
    costCategory: "€€",
    imageUrls: [
      "https://images.unsplash.com/photo-1581091012184-7e0cdfbb6797?w=800&q=80&fit=crop",
      "https://images.unsplash.com/photo-1562584942-61803c6ae7a2?w=800&q=80&fit=crop",
      "https://images.unsplash.com/photo-1695580140158-a49c79d2b8c8?w=800&q=80&fit=crop",
      "https://images.unsplash.com/photo-1678978926004-5243440ab143?w=800&q=80&fit=crop",
      "https://images.unsplash.com/photo-1590077428593-a55bb07c4665?w=800&q=80&fit=crop",
    ],
    imageAlts: [
      "Cala Mondragó türkiz öböl",
      "Mallorca fehér homokos strand",
      "Mallorca tengerpart heggyel",
      "Palma de Mallorca katedrális",
      "Mallorca tengerparti város",
    ],
    fallbackGradient: "from-orange-300 to-rose-500",
    fallbackEmoji: "🇪🇸",
  },
  {
    id: "torokorszag-all-inclusive",
    name: "Törökország All-Inclusive",
    description:
      "Az all-inclusive nyaralók királya. Hatalmas resortok, végtelen büfé, vízicsúszdák, animáció és meleg tenger.",
    highlights: [
      "All-inclusive király",
      "Víziparkok",
      "Animáció",
      "Meleg tenger",
    ],
    pros: [
      "A legjobb all-inclusive élmény a pénzedért — MINDENT tartalmaz",
      "Hatalmas resortok vízicsúszdákkal, animációval — gyerekparadicsom",
      "3 óra alatt ott vagy, közvetlen járat",
      "Meleg tenger, hosszú strandok, garantált napsütés",
    ],
    bestFor:
      "Aki gondtalan, mindent-tartalmaz nyaralást akar: enni-inni-úszni-csúszdázni, és fontos, hogy olcsó legyen.",
    programs: [
      "🏊 Resort vízipark és csúszdák egész nap",
      "🎭 Animációs programok (gyerekklub, esti show)",
      "🛁 Török fürdő (hamam) élmény",
      "🛍️ Bazár és helyi piac (alkudozás!)",
      "🚤 Hajókirándulás a partmentén",
      "🏛️ Antik romok: Ephesus, Aspendos, Side",
      "🍢 Török street food: kebab, pide, baklava",
      "🎈 Kappadókia napi kirándulás (hőlégballonozás!)",
    ],
    comparison:
      "A legolcsóbb all-inclusive opció, jobb resort-szolgáltatás, mint bárhol Európában. A görög szigeteknél rosszabb a strandok tisztasága, de a resort-élmény sokkal jobb. A Dominikai Köztársaságnál közelebb és olcsóbb.",
    travelTime: "~2.5-3 óra (közvetlen járat)",
    costCategory: "€€",
    imageUrls: [
      "https://images.unsplash.com/photo-1596394516093-501ba68a0ba6?w=800&q=80&fit=crop",
      "https://images.unsplash.com/photo-1605008409474-f9d401de8a78?w=800&q=80&fit=crop",
      "https://images.unsplash.com/photo-1577655197620-704858b270ac?w=800&q=80&fit=crop",
      "https://images.unsplash.com/photo-1591604129939-f1efa4d9f7fa?w=800&q=80&fit=crop",
      "https://images.unsplash.com/photo-1605303012903-c73d3e6e8039?w=800&q=80&fit=crop",
    ],
    imageAlts: [
      "All-inclusive resort medence és csúszdák",
      "Török tengerpart nyugágy",
      "Török bazár színes fűszerek",
      "Antik római romok",
      "Hagyományos török fürdő",
    ],
    fallbackGradient: "from-red-400 to-amber-500",
    fallbackEmoji: "🇹🇷",
  },
  {
    id: "zakynthos",
    name: "Zakynthos",
    description:
      "A világhírű Navagio (Hajótörés) strand hazája. Lenyűgöző sziklafalak, kristálytiszta víz és görög hangulat.",
    highlights: [
      "Navagio strand",
      "Caretta teknősök",
      "Kék barlangok",
      "Görög hangulat",
    ],
    pros: [
      "A Navagio strand az egyik legikonikusabb hely a Földön",
      "Caretta-caretta tengeri teknősök — gyerekeknek fantasztikus",
      "Kék barlangok: varázslatos hajókirándulás",
      "Autentikus görög tavernák és helyi borok",
    ],
    bestFor:
      "Aki az Instagramról ismert ikonikus strandot akarja látni, és szereti a görög hangulatot. Családoknak tökéletes.",
    programs: [
      "🚢 Navagio (Shipwreck) strand hajókirándulás",
      "🐢 Teknős-figyelés a Laganas-öbölben",
      "🔵 Kék barlangok túra csónakkal",
      "🏖️ Strandolás: Laganas, Gerakas, Porto Limnionas",
      "🍷 Görög borkóstoló és taverna este",
      "🚗 Sziget körbejárás autóval",
      "⛰️ Kilátópont a Navagio-strand fölött",
    ],
    comparison:
      "A legikonikusabb görög sziget a Navagio strand miatt. Krétánál kisebb és kevesebb a program, de a strand-élmény koncentráltabb. Kefalóniához és Lefkadához hasonló vízminőség.",
    travelTime: "~2-2.5 óra (közvetlen járat szezonban)",
    costCategory: "€€",
    imageUrls: [
      "https://images.unsplash.com/photo-1530841377377-3ff06c0ca713?w=800&q=80&fit=crop",
      "https://images.unsplash.com/photo-1589140592598-91853cbbc95b?w=800&q=80&fit=crop",
      "https://images.unsplash.com/photo-1570303380511-42219cf3e119?w=800&q=80&fit=crop",
      "https://images.unsplash.com/photo-1692662045267-c9fbae58254e?w=800&q=80&fit=crop",
      "https://images.unsplash.com/photo-1688406810599-979dd379ae98?w=800&q=80&fit=crop",
    ],
    imageAlts: [
      "Navagio hajótörött hajó strand",
      "Zakynthos légi panoráma",
      "Navagio-öböl felülről",
      "Zakynthos kék barlangok sziklái",
      "Zakynthos tengerpart légi fotó",
    ],
    fallbackGradient: "from-sky-400 to-blue-700",
    fallbackEmoji: "🚢",
  },
  {
    id: "kreta",
    name: "Kréta",
    description:
      "Görögország legnagyobb szigete, végtelen választékkal: rózsaszín homokos strandok, ősrégi romok, szurdokok és a világ legjobb görög konyhája.",
    highlights: [
      "Elafonisi strand",
      "Balos lagúna",
      "Szamariá-szurdok",
      "Görög gasztronómia",
    ],
    pros: [
      "A legtöbb program egy görög szigeten — soha nem lesz unalmas",
      "Elafonisi rózsaszín strand és Balos lagúna: világ TOP 10 strand",
      "Autentikus görög falvak, ahol az idő megállt",
      "A legjobb görög konyha: friss hal, olíva, feta, raki",
    ],
    bestFor:
      "Aki mindent akar: strandot, túrázást, kultúrát, gasztronómiát — és nem akar választani. A legsokoldalúbb görög sziget.",
    programs: [
      "🏖️ Elafonisi rózsaszín strand (csoda!)",
      "🌊 Balos lagúna hajókirándulás",
      "🥾 Szamariá-szurdok túra (16 km, lenyűgöző!)",
      "🏛️ Knósszoszi palota — minószi civilizáció",
      "🍽️ Görög főzőtanfolyam helyi alapanyagokkal",
      "🐙 Hagyományos halász-taverna vacsorák",
      "🚗 Autós körtúra: Réthymno, Chania, Agios Nikolaos",
      "🍷 Raki kóstoló és olívaolaj-készítés",
    ],
    comparison:
      "A legnagyobb és legváltozatosabb görög sziget. Több program, mint Zakynthosnak vagy Kefalóniának, de a strandok nem annyira koncentráltak. Az ár-érték arány kiváló.",
    travelTime: "~2.5-3 óra (közvetlen járat)",
    costCategory: "€€",
    imageUrls: [
      "https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?w=800&q=80&fit=crop",
      "https://images.unsplash.com/photo-1580837119756-563d608dd119?w=800&q=80&fit=crop",
      "https://images.unsplash.com/photo-1601581875039-62bd4dd74b37?w=800&q=80&fit=crop",
      "https://images.unsplash.com/photo-1605786005843-789095e12c47?w=800&q=80&fit=crop",
      "https://images.unsplash.com/photo-1626252577185-ec3a6d3da2a0?w=800&q=80&fit=crop",
    ],
    imageAlts: [
      "Balos lagúna légi fotó",
      "Elafonisi rózsaszín homok",
      "Szamariá-szurdok sziklái",
      "Chania velencés kikötő",
      "Görög hal taverna",
    ],
    fallbackGradient: "from-blue-400 to-emerald-500",
    fallbackEmoji: "🏛️",
  },
  {
    id: "kefalonia",
    name: "Kefalónia",
    description:
      "Görög szépség a Jón-tengerben: Myrtos strand a világ egyik legszebb strandja. Kisebb turizmus, hamisítatlan görög élet.",
    highlights: [
      "Myrtos strand",
      "Melissani-barlang",
      "Fiskardo",
      "Autentikus görög",
    ],
    pros: [
      "Myrtos strand — a kilátás lélegzetelállító, a víz irreálisan kék",
      "Melissani-barlang: csónaktúra egy napfényes barlangban",
      "Fiskardo: a legszebb görög kikötőfalu",
      "Kevesebb turista, mint Zakynthoson — autentikusabb élmény",
    ],
    bestFor:
      "Aki csendes, autentikus görög nyaralást akar lélegzetelállító strandokkal. Nem buliszigett, hanem nyugalom.",
    programs: [
      "🏖️ Myrtos strand nap (az a kilátás fentről!)",
      "⛵ Melissani-barlang csónaktúra",
      "🏘️ Fiskardo kikötő séta és vacsora",
      "🐚 Antisamos strand (Captain Corelli forgatási helyszín)",
      "🚗 Sziget körbejárása autóval",
      "🍯 Helyi méz- és borkóstoló",
      "🚤 Napi hajókirándulás Ithaka szigetére",
    ],
    comparison:
      "Zakynthoshoz hasonló vízminőség, de sokkal nyugodtabb. Krétánál kisebb, kevesebb program, de a Myrtos-élmény önmagában megéri.",
    travelTime: "~2.5-3 óra (átszállással / charter)",
    costCategory: "€€",
    imageUrls: [
      "https://images.unsplash.com/photo-1585102040911-925def363f64?w=800&q=80&fit=crop",
      "https://images.unsplash.com/photo-1573316131382-ba2893f2e173?w=800&q=80&fit=crop",
      "https://images.unsplash.com/photo-1565135100468-bca371a4e4ed?w=800&q=80&fit=crop",
      "https://images.unsplash.com/photo-1559576642-70cb962f213f?w=800&q=80&fit=crop",
      "https://images.unsplash.com/photo-1530618111505-2d458c0f1ab8?w=800&q=80&fit=crop",
    ],
    imageAlts: [
      "Myrtos strand türkiz tenger",
      "Kefalónia hegy és tengerpart",
      "Kefalónia strand légi fotó",
      "Kefalónia öböl madártávlatból",
      "Kefalónia naplemente a tengernél",
    ],
    fallbackGradient: "from-cyan-400 to-blue-500",
    fallbackEmoji: "⛵",
  },
  {
    id: "rodosz",
    name: "Rodosz",
    description:
      "Történelem és tengerpart együtt: középkori óváros (UNESCO), antik romok és gyönyörű strandok.",
    highlights: [
      "UNESCO óváros",
      "Lindos akropolisz",
      "Történelmi kincsek",
      "Napsütés",
    ],
    pros: [
      "Középkori óváros — olyan, mintha időutazásra mennél",
      "Lindos akropolisza és fehér falú falu: mesebeli",
      "A legtöbb napsütéses nap egész Európában",
      "Történelem és strand tökéletes kombinációja",
    ],
    bestFor:
      "Aki strandolás mellett kultúrát és történelmet is akar. A legtöbb 'látnivaló' egy görög szigeten.",
    programs: [
      "🏰 Középkori óváros felfedezése (UNESCO!)",
      "🏛️ Lindos akropolisza + strand alatta",
      "🦋 Pillangók völgye természetvédelmi terület",
      "🏖️ Tsambika és Faliraki strandok",
      "⚔️ Nagymesterek palotája",
      "🚤 Hajókirándulás Symi szigetére (színes házak!)",
      "🍽️ Óvárosi taverna-hopping este",
    ],
    comparison:
      "A legtöbb látnivaló egy görög szigeten. Krétához hasonlóan sokoldalú, de a középkori óváros egyedülálló.",
    travelTime: "~2.5-3 óra (közvetlen járat szezonban)",
    costCategory: "€€",
    imageUrls: [
      "https://images.unsplash.com/photo-1555993539-1732b0258235?w=800&q=80&fit=crop",
      "https://images.unsplash.com/photo-1601309994242-480a2e8e0f08?w=800&q=80&fit=crop",
      "https://images.unsplash.com/photo-1561815230-33b6ed4bd01c?w=800&q=80&fit=crop",
      "https://images.unsplash.com/photo-1571406252256-a6f1b048a6b8?w=800&q=80&fit=crop",
      "https://images.unsplash.com/photo-1626252577185-ec3a6d3da2a0?w=800&q=80&fit=crop",
    ],
    imageAlts: [
      "Rodosz középkori óváros kövezet",
      "Lindos fehér házak és akropolisz",
      "Pillangók völgye",
      "Tsambika strand",
      "Symi sziget színes házak",
    ],
    fallbackGradient: "from-amber-300 to-orange-500",
    fallbackEmoji: "🏰",
  },
  {
    id: "lefkada",
    name: "Lefkada",
    description:
      "A Karib-tenger Görögországban! Porto Katsiki és Egremni strandjai minden képzeletet felülmúlnak.",
    highlights: [
      "Porto Katsiki",
      "Egremni strand",
      "Híddal elérhető",
      "Olcsó",
    ],
    pros: [
      "Porto Katsiki Európa TOP 3 strandja — és tényleg karibi vizet kapsz",
      "Autós híddal elérhető — nem kell kompra várni!",
      "A legolcsóbb a görög szigetek közül",
      "Nidri és Vasiliki: bájosak és nem turistásak",
    ],
    bestFor:
      "Aki karibi minőségű strandokat akar Európában, fillérekért. A legjobb ár-érték arány a görög szigetek között.",
    programs: [
      "🏖️ Porto Katsiki nap (a lépcsőn lefelé a kilátás!)",
      "🏖️ Egremni strand fehér sziklákkal",
      "⛵ Vitorlázás a Jón-tengeren",
      "🏘️ Nidri falu séta és kikötő",
      "🏄 Vasiliki — Európa egyik legjobb szörf-spotja",
      "🚤 Napi hajókirándulás Meganisi vagy Kefalónia felé",
      "🍽️ Tengerparti taverna friss hallal",
    ],
    comparison:
      "A strandok vetekszenek Zakynthossal és Kefalóniával, de olcsóbb és könnyebben elérhető (híd!). Az igazi 'rejtett kincs'.",
    travelTime: "~2-2.5 óra repülő + 1 óra autó",
    costCategory: "€-€€",
    imageUrls: [
      "https://images.unsplash.com/photo-1583896379253-6ed992a3c77a?w=800&q=80&fit=crop",
      "https://images.unsplash.com/photo-1658957470845-538d2f755b72?w=800&q=80&fit=crop",
      "https://images.unsplash.com/photo-1596708171825-0739dd4e8621?w=800&q=80&fit=crop",
      "https://images.unsplash.com/photo-1632558453702-d928a5d4af02?w=800&q=80&fit=crop",
      "https://images.unsplash.com/photo-1604260618036-efac1d586f96?w=800&q=80&fit=crop",
    ],
    imageAlts: [
      "Porto Katsiki strand felülről",
      "Lefkada türkiz strand",
      "Lefkada tengerpart zöld hegyekkel",
      "Lépcső a strandra vezet",
      "Csónak a parton Lefkadán",
    ],
    fallbackGradient: "from-sky-300 to-indigo-500",
    fallbackEmoji: "🏖️",
  },
  {
    id: "skiathosz",
    name: "Skiathosz",
    description:
      "60+ strand egyetlen kis szigeten! Koukounaries strand Európa egyik legszebb homokos strandja.",
    highlights: [
      "60+ strand",
      "Koukounaries",
      "Mamma Mia közelben",
      "Pezsgő nightlife",
    ],
    pros: [
      "60+ strand egy aprócska szigeten — minden nap másik strand!",
      "Koukounaries: fenyőfákkal körülvett fehér homokos strand",
      "Élénk kikötő és pezsgő éjszakai élet",
      "Mamma Mia! forgatási helyszíne (Skopelos) közel van",
    ],
    bestFor:
      "Aki strandváltozatosságot, görög charmot és este egy kis bulit is akar. A legpezsgőbb a kis görög szigetek közül.",
    programs: [
      "🏖️ Strandhopping: Koukounaries, Lalaria, Banana Beach",
      "🚤 Hajókirándulás Skopelos-ra (Mamma Mia!)",
      "🌲 Túra a fenyőerdőben a sziget belsejében",
      "🏘️ Skiathosz Town kikötő séta és shopping",
      "🍸 Éjszakai élet a kikötő bárjaiban",
      "🐚 Lalaria strand — fehér kavicsos, csak hajóval elérhető",
      "🧘 Jóga a tengerparton napfelkeltére",
    ],
    comparison:
      "A legkisebb és legpezsgőbb a görög opciók közül. Kevesebb a 'nagystrandok', de a strandok száma és változatossága páratlan.",
    travelTime: "~2.5-3 óra (közvetlen charter / átszállással)",
    costCategory: "€€",
    imageUrls: [
      "https://images.unsplash.com/photo-1606847053098-4f7f4f5ab1c5?w=800&q=80&fit=crop",
      "https://images.unsplash.com/photo-1606847664754-8fd9a2dc7b37?w=800&q=80&fit=crop",
      "https://images.unsplash.com/photo-1624481924435-c517c96289c7?w=800&q=80&fit=crop",
      "https://images.unsplash.com/photo-1600278495861-4bff1c2f10a9?w=800&q=80&fit=crop",
      "https://images.unsplash.com/photo-1630491571415-2345e809331c?w=800&q=80&fit=crop",
    ],
    imageAlts: [
      "Skiathosz sziklás part zöld fákkal",
      "Skiathosz strand csónakokkal",
      "Skiathosz légi fotó zöld erdő és kék tenger",
      "Skiathosz fenyőfák a tenger mellett",
      "Skiathosz homokos strand",
    ],
    fallbackGradient: "from-green-400 to-teal-500",
    fallbackEmoji: "🌊",
  },
];
