import { Destination } from "./types";

export const destinations: Destination[] = [
  {
    id: "seychelles",
    name: "Seychelles",
    description:
      "A Földi Paradicsom. Gránit sziklák közötti strandok, kristálytiszta víz és érintetlen természet. A világ legszebb strandjai itt vannak.",
    highlights: [
      "Világ legszebb strandjai",
      "Gránit sziklák",
      "Érintetlen természet",
      "Exkluzív élmény",
    ],
    pros: [
      "Az Anse Source d'Argent világ TOP 3 strandja",
      "Érintetlen, vadregényes természet — nem tömeges turizmus",
      "Egyedülálló gránit sziklás tájkép, ami sehol máshol nincs",
      "Teknősök, trópusi madarak, korallzátonyok",
    ],
    bestFor:
      "Aki a világ legszebb strandjait akarja látni, és nem baj, ha prémium áron. Romantikus + természetközeli.",
    programs: [
      "🏖️ Anse Source d'Argent — a legikonikusabb strand",
      "🐢 Óriás teknős rezervátum (Aldabra teknősök!)",
      "🤿 Snorkelezés és búvárkodás korallzátonyoknál",
      "🥾 Morne Seychellois Nemzeti Park túra",
      "🚤 Szigethopping csónakkal",
      "🌅 Naplemente a gránit sziklák között",
    ],
    comparison:
      "A Maldívokhoz hasonlóan luxus kategória, de itt a strandok sokkal változatosabbak (gránit sziklák!). Drágább, mint bármelyik európai opció, de az élmény is más liga.",
    travelTime: "~12-13 óra (1 átszállással)",
    costCategory: "€€€€",
    imageUrls: [
      "https://images.unsplash.com/photo-1589979481223-deb893043163?w=800&q=80&fit=crop",
      "https://images.unsplash.com/photo-1609137144813-7d9921338f24?w=800&q=80&fit=crop",
      "https://images.unsplash.com/photo-1551244072-5d12893278ab?w=800&q=80&fit=crop",
      "https://images.unsplash.com/photo-1590523741831-ab7e8b8f9c7f?w=800&q=80&fit=crop",
      "https://images.unsplash.com/photo-1583417319070-4a69db38a482?w=800&q=80&fit=crop",
    ],
    imageAlts: [
      "Anse Source d'Argent gránit sziklái",
      "Teknős a parton",
      "Kristálytiszta víz korallzátonnyal",
      "Trópusi növényzet",
      "Pálmafák és türkiz tenger",
    ],
    fallbackGradient: "from-teal-300 to-cyan-600",
    fallbackEmoji: "🪨",
    youtubeVideoId: "5iPsomVxXpE",
  },

  {
    id: "mallorca",
    name: "Mallorca",
    description:
      "Spanyol sziget a Földközi-tengeren: gyönyörű öblök, finom tapas, és a családi nyaralás klasszikusa.",
    highlights: [
      "Gyönyörű öblök",
      "Spanyol konyha",
      "Családbarát",
      "Rövid repülőút",
    ],
    pros: [
      "3 óra alatt ott vagy — a legrövidebb utazás az egzotikusabb célok közül",
      "Gyönyörű türkiz öblök (Cala d'Or, Cala Millor, Cala Mondragó)",
      "Palma de Mallorca pezsgő óvárosa, piacok, éttermek",
      "Autóval körbejárható, rugalmas programok",
    ],
    bestFor:
      "Aki szép strandokat és spanyol hangulatot akar rövid repülőúttal, és fontos a rugalmasság.",
    programs: [
      "🏖️ Cala-hopping: Cala d'Or, Mondragó, Varques",
      "🏰 Palma de Mallorca óváros és katedrális",
      "🚗 Autós körtúra a Serra de Tramuntana hegységben",
      "🍷 Borkóstoló helyi pincészetben",
      "🚴 Kerékpár túra (a profik is itt edznek!)",
      "🌊 Csónaktúra a Drach-barlangokhoz",
      "🍤 Tapas-est Palma óvárosában",
    ],
    comparison:
      "A görög szigetekhez hasonló távolság és árkategória, de spanyol hangulat görög helyett. A strand-minőségben a görög szigetek nyernek, de Mallorca rugalmasabb (autóval járható, több a program).",
    travelTime: "~2.5-3 óra (közvetlen járat)",
    costCategory: "€€",
    imageUrls: [
      "https://images.unsplash.com/photo-1562584942-61803c6ae7a2?w=800&q=80&fit=crop",
      "https://images.unsplash.com/photo-1695580140158-a49c79d2b8c8?w=800&q=80&fit=crop",
      "https://images.unsplash.com/photo-1678978926004-5243440ab143?w=800&q=80&fit=crop",
      "https://images.unsplash.com/photo-1590077428593-a55bb07c4665?w=800&q=80&fit=crop",
    ],
    imageAlts: [
      "Cala Mondragó türkiz öböl",
      "Mallorca fehér homokos strand",
      "Mallorca tengerpart heggyel",
      "Palma de Mallorca katedrális",
      "Mallorca tengerparti város",
    ],
    fallbackGradient: "from-orange-300 to-rose-500",
    fallbackEmoji: "🇪🇸",
    youtubeVideoId: "7boYP13LwDs",
  },
  {
    id: "torokorszag-all-inclusive",
    name: "Törökország All-Inclusive",
    description:
      "Az all-inclusive nyaralók királya. Hatalmas resortok, végtelen büfé, vízicsúszdák, animáció és meleg tenger.",
    highlights: [
      "All-inclusive király",
      "Víziparkok",
      "Animáció",
      "Meleg tenger",
    ],
    pros: [
      "A legjobb all-inclusive élmény a pénzedért — MINDENT tartalmaz",
      "Hatalmas resortok vízicsúszdákkal, animációval — gyerekparadicsom",
      "3 óra alatt ott vagy, közvetlen járat",
      "Meleg tenger, hosszú strandok, garantált napsütés",
    ],
    bestFor:
      "Aki gondtalan, mindent-tartalmaz nyaralást akar: enni-inni-úszni-csúszdázni, és fontos, hogy olcsó legyen.",
    programs: [
      "🏊 Resort vízipark és csúszdák egész nap",
      "🎭 Animációs programok (gyerekklub, esti show)",
      "🛁 Török fürdő (hamam) élmény",
      "🛍️ Bazár és helyi piac (alkudozás!)",
      "🚤 Hajókirándulás a partmentén",
      "🏛️ Antik romok: Ephesus, Aspendos, Side",
      "🍢 Török street food: kebab, pide, baklava",
      "🎈 Kappadókia napi kirándulás (hőlégballonozás!)",
    ],
    comparison:
      "A legolcsóbb all-inclusive opció, jobb resort-szolgáltatás, mint bárhol Európában. A görög szigeteknél rosszabb a strandok tisztasága, de a resort-élmény sokkal jobb. A Dominikai Köztársaságnál közelebb és olcsóbb.",
    travelTime: "~2.5-3 óra (közvetlen járat)",
    costCategory: "€€",
    imageUrls: [
      "https://images.unsplash.com/photo-1730825109888-c13511e22500?w=800&q=80&fit=crop",
      "https://images.unsplash.com/premium_photo-1661963652315-d5a9d26637dd?w=800&q=80&fit=crop",
      "https://images.unsplash.com/photo-1629649407271-2dac934c1f1b?w=800&q=80&fit=crop",
      "https://images.unsplash.com/photo-1730825089900-6c6ec7846d51?w=800&q=80&fit=crop",
      "https://images.unsplash.com/photo-1609932937042-56e6bdd7a41b?w=800&q=80&fit=crop",
    ],
    imageAlts: [
      "Antalya türkiz tengerpart",
      "Kappadókia tájkép",
      "Török bazár színes fűszerek",
      "Antalya part felülről",
      "Kappadókia hőlégballonok",
    ],
    fallbackGradient: "from-red-400 to-amber-500",
    fallbackEmoji: "🇹🇷",
    youtubeVideoId: "Eljk-iTliFI",
  },
  {
    id: "zakynthos",
    name: "Zakynthos",
    description:
      "A világhírű Navagio (Hajótörés) strand hazája. Lenyűgöző sziklafalak, kristálytiszta víz és görög hangulat.",
    highlights: [
      "Navagio strand",
      "Caretta teknősök",
      "Kék barlangok",
      "Görög hangulat",
    ],
    pros: [
      "A Navagio strand az egyik legikonikusabb hely a Földön",
      "Caretta-caretta tengeri teknősök — gyerekeknek fantasztikus",
      "Kék barlangok: varázslatos hajókirándulás",
      "Autentikus görög tavernák és helyi borok",
    ],
    bestFor:
      "Aki az Instagramról ismert ikonikus strandot akarja látni, és szereti a görög hangulatot. Családoknak tökéletes.",
    programs: [
      "🚢 Navagio (Shipwreck) strand hajókirándulás",
      "🐢 Teknős-figyelés a Laganas-öbölben",
      "🔵 Kék barlangok túra csónakkal",
      "🏖️ Strandolás: Laganas, Gerakas, Porto Limnionas",
      "🍷 Görög borkóstoló és taverna este",
      "🚗 Sziget körbejárás autóval",
      "⛰️ Kilátópont a Navagio-strand fölött",
    ],
    comparison:
      "A legikonikusabb görög sziget a Navagio strand miatt. Krétánál kisebb és kevesebb a program, de a strand-élmény koncentráltabb. Kefalóniához és Lefkadához hasonló vízminőség.",
    travelTime: "~2-2.5 óra (közvetlen járat szezonban)",
    costCategory: "€€",
    imageUrls: [
      "https://images.unsplash.com/photo-1530841377377-3ff06c0ca713?w=800&q=80&fit=crop",
      "https://images.unsplash.com/photo-1589140592598-91853cbbc95b?w=800&q=80&fit=crop",
      "https://images.unsplash.com/photo-1570303380511-42219cf3e119?w=800&q=80&fit=crop",
      "https://images.unsplash.com/photo-1692662045267-c9fbae58254e?w=800&q=80&fit=crop",
      "https://images.unsplash.com/photo-1688406810599-979dd379ae98?w=800&q=80&fit=crop",
    ],
    imageAlts: [
      "Navagio hajótörött hajó strand",
      "Zakynthos légi panoráma",
      "Navagio-öböl felülről",
      "Zakynthos kék barlangok sziklái",
      "Zakynthos tengerpart légi fotó",
    ],
    fallbackGradient: "from-sky-400 to-blue-700",
    fallbackEmoji: "🚢",
    youtubeVideoId: "5ZxApiwDecQ",
  },
  {
    id: "kreta",
    name: "Kréta",
    description:
      "Görögország legnagyobb szigete, végtelen választékkal: rózsaszín homokos strandok, ősrégi romok, szurdokok és a világ legjobb görög konyhája.",
    highlights: [
      "Elafonisi strand",
      "Balos lagúna",
      "Szamariá-szurdok",
      "Görög gasztronómia",
    ],
    pros: [
      "A legtöbb program egy görög szigeten — soha nem lesz unalmas",
      "Elafonisi rózsaszín strand és Balos lagúna: világ TOP 10 strand",
      "Autentikus görög falvak, ahol az idő megállt",
      "A legjobb görög konyha: friss hal, olíva, feta, raki",
    ],
    bestFor:
      "Aki mindent akar: strandot, túrázást, kultúrát, gasztronómiát — és nem akar választani. A legsokoldalúbb görög sziget.",
    programs: [
      "🏖️ Elafonisi rózsaszín strand (csoda!)",
      "🌊 Balos lagúna hajókirándulás",
      "🥾 Szamariá-szurdok túra (16 km, lenyűgöző!)",
      "🏛️ Knósszoszi palota — minószi civilizáció",
      "🍽️ Görög főzőtanfolyam helyi alapanyagokkal",
      "🐙 Hagyományos halász-taverna vacsorák",
      "🚗 Autós körtúra: Réthymno, Chania, Agios Nikolaos",
      "🍷 Raki kóstoló és olívaolaj-készítés",
    ],
    comparison:
      "A legnagyobb és legváltozatosabb görög sziget. Több program, mint Zakynthosnak vagy Kefalóniának, de a strandok nem annyira koncentráltak. Az ár-érték arány kiváló.",
    travelTime: "~2.5-3 óra (közvetlen járat)",
    costCategory: "€€",
    imageUrls: [
      "https://images.unsplash.com/photo-1661806786033-7ac31baa448a?w=800&q=80&fit=crop",
      "https://images.unsplash.com/premium_photo-1675747631203-f3a7431486c8?w=800&q=80&fit=crop",
      "https://images.unsplash.com/photo-1665578446842-c23fa59d9438?w=800&q=80&fit=crop",
      "https://images.unsplash.com/photo-1667384618777-94f1860dfd6d?w=800&q=80&fit=crop",
      "https://images.unsplash.com/photo-1665578448604-36fa87710850?w=800&q=80&fit=crop",
    ],
    imageAlts: [
      "Balos lagúna légi fotó",
      "Elafonisi rózsaszín homok",
      "Chania velencés kikötő",
      "Balos lagúna türkiz víz",
      "Chania óváros",
    ],
    fallbackGradient: "from-blue-400 to-emerald-500",
    fallbackEmoji: "🏛️",
    youtubeVideoId: "paXLik5tgYg",
  },
  {
    id: "rodosz",
    name: "Rodosz",
    description:
      "Történelem és tengerpart együtt: középkori óváros (UNESCO), antik romok és gyönyörű strandok.",
    highlights: [
      "UNESCO óváros",
      "Lindos akropolisz",
      "Történelmi kincsek",
      "Napsütés",
    ],
    pros: [
      "Középkori óváros — olyan, mintha időutazásra mennél",
      "Lindos akropolisza és fehér falú falu: mesebeli",
      "A legtöbb napsütéses nap egész Európában",
      "Történelem és strand tökéletes kombinációja",
    ],
    bestFor:
      "Aki strandolás mellett kultúrát és történelmet is akar. A legtöbb 'látnivaló' egy görög szigeten.",
    programs: [
      "🏰 Középkori óváros felfedezése (UNESCO!)",
      "🏛️ Lindos akropolisza + strand alatta",
      "🦋 Pillangók völgye természetvédelmi terület",
      "🏖️ Tsambika és Faliraki strandok",
      "⚔️ Nagymesterek palotája",
      "🚤 Hajókirándulás Symi szigetére (színes házak!)",
      "🍽️ Óvárosi taverna-hopping este",
    ],
    comparison:
      "A legtöbb látnivaló egy görög szigeten. Krétához hasonlóan sokoldalú, de a középkori óváros egyedülálló.",
    travelTime: "~2.5-3 óra (közvetlen járat szezonban)",
    costCategory: "€€",
    imageUrls: [
      "https://images.unsplash.com/photo-1588335553332-3f5b7aa37574?w=800&q=80&fit=crop",
      "https://images.unsplash.com/premium_photo-1754255009294-afb23750a33e?w=800&q=80&fit=crop",
      "https://images.unsplash.com/photo-1588335553525-86334fca1d5a?w=800&q=80&fit=crop",
      "https://images.unsplash.com/photo-1740564769172-ae728185fd00?w=800&q=80&fit=crop",
      "https://images.unsplash.com/photo-1602522147042-2a8a364d09ce?w=800&q=80&fit=crop",
    ],
    imageAlts: [
      "Lindos fehér házak és akropolisz",
      "Rodosz középkori óváros",
      "Symi sziget színes házak",
      "Rodosz strand türkiz víz",
      "Lindos öböl felülről",
    ],
    fallbackGradient: "from-amber-300 to-orange-500",
    fallbackEmoji: "🏰",
    youtubeVideoId: "7wljcBBDfi8",
  },
  {
    id: "skiathosz",
    name: "Skiathosz",
    description:
      "60+ strand egyetlen kis szigeten! Koukounaries strand Európa egyik legszebb homokos strandja.",
    highlights: [
      "60+ strand",
      "Koukounaries",
      "Mamma Mia közelben",
      "Pezsgő nightlife",
    ],
    pros: [
      "60+ strand egy aprócska szigeten — minden nap másik strand!",
      "Koukounaries: fenyőfákkal körülvett fehér homokos strand",
      "Élénk kikötő és pezsgő éjszakai élet",
      "Mamma Mia! forgatási helyszíne (Skopelos) közel van",
    ],
    bestFor:
      "Aki strandváltozatosságot, görög charmot és este egy kis bulit is akar. A legpezsgőbb a kis görög szigetek közül.",
    programs: [
      "🏖️ Strandhopping: Koukounaries, Lalaria, Banana Beach",
      "🚤 Hajókirándulás Skopelos-ra (Mamma Mia!)",
      "🌲 Túra a fenyőerdőben a sziget belsejében",
      "🏘️ Skiathosz Town kikötő séta és shopping",
      "🍸 Éjszakai élet a kikötő bárjaiban",
      "🐚 Lalaria strand — fehér kavicsos, csak hajóval elérhető",
      "🧘 Jóga a tengerparton napfelkeltére",
    ],
    comparison:
      "A legkisebb és legpezsgőbb a görög opciók közül. Kevesebb a 'nagystrandok', de a strandok száma és változatossága páratlan.",
    travelTime: "~2.5-3 óra (közvetlen charter / átszállással)",
    costCategory: "€€",
    imageUrls: [
      "https://images.unsplash.com/photo-1606847053098-4f7f4f5ab1c5?w=800&q=80&fit=crop",
      "https://images.unsplash.com/photo-1606847664754-8fd9a2dc7b37?w=800&q=80&fit=crop",
      "https://images.unsplash.com/photo-1624481924435-c517c96289c7?w=800&q=80&fit=crop",
      "https://images.unsplash.com/photo-1600278495861-4bff1c2f10a9?w=800&q=80&fit=crop",
      "https://images.unsplash.com/photo-1630491571415-2345e809331c?w=800&q=80&fit=crop",
    ],
    imageAlts: [
      "Skiathosz sziklás part zöld fákkal",
      "Skiathosz strand csónakokkal",
      "Skiathosz légi fotó zöld erdő és kék tenger",
      "Skiathosz fenyőfák a tenger mellett",
      "Skiathosz homokos strand",
    ],
    fallbackGradient: "from-green-400 to-teal-500",
    fallbackEmoji: "🌊",
    youtubeVideoId: "6LlOzL0Peeg",
  },
  {
    id: "szardinia",
    name: "Szardínia",
    description:
      "Olaszország egzotikus szigete: smaragdzöld tenger, fehér homokos strandok, és a világ egyik legjobb olasz konyhája. A Costa Smeralda a mediterrán luxus csúcsa.",
    highlights: [
      "Costa Smeralda",
      "Smaragd tenger",
      "Olasz konyha",
      "Természetvédelem",
    ],
    pros: [
      "A Karib-tengerhez mérhető víz — de Európában, 2.5 óra repülővel",
      "Costa Smeralda: a világ egyik legexkluzívabb nyaralóhelye",
      "Olasz konyha a legjobb formájában: friss tenger gyümölcsei, porceddu, pecorino",
      "Változatos táj: sziklás öblök, homokos strandok, hegyek",
    ],
    bestFor:
      "Aki karibi minőségű vizet akar olasz gasztronómiával, és nem baj, ha kicsit exkluzívabb. Autóval járható, rugalmas nyaralás.",
    programs: [
      "🏖️ La Pelosa strand (Sardinia leghíresebb strandja)",
      "🌊 Costa Smeralda öblök felfedezése",
      "🚤 Hajókirándulás a La Maddalena szigetcsoporthoz",
      "🍝 Olasz gasztrotúra: porceddu, fregola, seadas",
      "🏘️ Alghero óváros séta (katalán örökség!)",
      "🤿 Snorkelezés kristálytiszta vízben",
      "🍷 Cannonau borkóstoló helyi pincészetben",
      "🏔️ Gorropu-szurdok túra",
    ],
    comparison:
      "Mallorcához hasonló koncepció (autós szigetnyaralás), de az olasz konyha és a vadregényesebb táj miatt más élmény. Drágább, mint a görög szigetek, de a víz és a gasztronómia kárpótol.",
    travelTime: "~2.5-3 óra (közvetlen járat szezonban)",
    costCategory: "€€-€€€",
    imageUrls: [
      "https://images.unsplash.com/photo-1698247186956-1a06d3c7fb6c?w=800&q=80&fit=crop",
      "https://images.unsplash.com/photo-1725260730815-98a3565d49b0?w=800&q=80&fit=crop",
      "https://images.unsplash.com/photo-1723800722565-c57e0821f8dd?w=800&q=80&fit=crop",
      "https://images.unsplash.com/photo-1723800598126-9c9dbb7ea271?w=800&q=80&fit=crop",
      "https://images.unsplash.com/photo-1725260730395-abd6b0585e29?w=800&q=80&fit=crop",
    ],
    imageAlts: [
      "Costa Smeralda smaragdzöld tenger",
      "Szardínia fehér homokos strand",
      "La Maddalena szigetcsoport",
      "Szardínia sziklás part",
      "Szardínia öböl felülről",
    ],
    fallbackGradient: "from-emerald-300 to-cyan-500",
    fallbackEmoji: "🇮🇹",
    youtubeVideoId: "mBw7vkcQOew",
  },
  {
    id: "horvatorszag",
    name: "Horvátország (Dubrovnik + Split)",
    description:
      "Az Adria gyöngyszemei: középkori falakkal körülvett Dubrovnik, Diocletianus palotája Split-ben, és a világ legtisztább tengere a szigeteken.",
    highlights: [
      "Dubrovnik óváros",
      "Game of Thrones",
      "Adriai szigetek",
      "Plitvicei-tavak",
    ],
    pros: [
      "Dubrovnik óvárosa a világ egyik legszebb városa — UNESCO örökség",
      "Autóval is elérhető Budapestről (7-8 óra)",
      "Kristálytiszta Adria — a Földközi-tenger legtisztább vize",
      "Plitvicei-tavak: mesebeli vízesések és tavak",
    ],
    bestFor:
      "Aki kultúrát, történelmet és gyönyörű tengert akar, autóval is elérhető távolságban. Rugalmas, road trip jellegű nyaralás.",
    programs: [
      "🏰 Dubrovnik fal-séta (az óváros körül, tengerre néző kilátás)",
      "⚔️ Game of Thrones túra King's Landing helyszínein",
      "🏛️ Diocletianus palotája Splitben",
      "🏝️ Hvar sziget: levendula, borok, éjszakai élet",
      "💧 Plitvicei-tavak Nemzeti Park (vízesések!)",
      "🚤 Hajókirándulás az Elafiti-szigetekre",
      "🍽️ Dalmát vacsora: fekete rizottó, osztriga, pašticada",
      "🛶 Kajakozás Dubrovnik falai mellett",
    ],
    comparison:
      "A görög szigeteknél közelebb van és autóval is elérhető. A történelmi látnivalók gazdagabbak, mint bármelyik görög szigeten. A strandok sziklásabbak, de a víz kristálytiszta.",
    travelTime: "~7-8 óra autóval / ~1.5 óra repülővel",
    costCategory: "€€",
    imageUrls: [
      "https://images.unsplash.com/premium_photo-1661963921028-aded38f2fb64?w=800&q=80&fit=crop",
      "https://images.unsplash.com/premium_photo-1661963768884-ec6e7eaf657a?w=800&q=80&fit=crop",
      "https://images.unsplash.com/premium_photo-1661963912299-4848fd629f2d?w=800&q=80&fit=crop",
      "https://images.unsplash.com/premium_photo-1661887156382-edf8a21e4c28?w=800&q=80&fit=crop",
      "https://images.unsplash.com/photo-1612806016377-72364965a3b7?w=800&q=80&fit=crop",
    ],
    imageAlts: [
      "Dubrovnik óváros fal és tenger",
      "Split Diocletianus palotája",
      "Plitvicei-tavak vízesés",
      "Hvar sziget öböl",
      "Dubrovnik narancssárga tetők felülről",
    ],
    fallbackGradient: "from-blue-500 to-red-500",
    fallbackEmoji: "🏰",
    youtubeVideoId: "4tPG4z2HeXg",
  },
  {
    id: "szicilia",
    name: "Szicília",
    description:
      "Olaszország legnagyobb szigete: aktív vulkán, ókori görög templomok, és a világ legjobb street food-ja. A történelem és a gasztronómia paradicsoma.",
    highlights: [
      "Etna vulkán",
      "Ókori romok",
      "Street food király",
      "Barokk városok",
    ],
    pros: [
      "Etna vulkán — aktív vulkánt nehéz máshol megmászni Európában",
      "A világ legjobb street food-ja: arancini, cannoli, granita",
      "UNESCO barokk városok: Noto, Ragusa, Modica",
      "Ókori görög templomok: Agrigento, Siracusa, Taormina",
    ],
    bestFor:
      "Aki gasztronómiát, kultúrát és természeti csodát akar egy helyen. Nem tipikus strandnyaralás, hanem kaland + strand.",
    programs: [
      "🌋 Etna vulkán túra (Európa legnagyobb aktív vulkánja!)",
      "🏛️ Agrigento Templomok Völgye (ókori görög romok)",
      "🍦 Szicíliai street food túra: arancini, cannoli, granita",
      "🏘️ Taormina: mesebeli város az Etna lábánál",
      "🏖️ San Vito Lo Capo: Szicília legszebb strandja",
      "🎭 Barokk Noto és Ragusa (UNESCO!)",
      "🍷 Szicíliai borkóstoló: Nero d'Avola, Etna Rosso",
      "🐟 Halpiac Cataniában és friss hal vacsora",
    ],
    comparison:
      "Krétához hasonlóan sokoldalú: történelem + strand + gasztronómia. De az Etna vulkán és az olasz street food egyedülálló. Mallorcánál változatosabb, a görög szigeteknél gazdagabb gasztronómia.",
    travelTime: "~2.5-3 óra (közvetlen járat szezonban)",
    costCategory: "€€",
    imageUrls: [
      "https://images.unsplash.com/premium_photo-1749846961904-3b110083a024?w=800&q=80&fit=crop",
      "https://images.unsplash.com/photo-1664481775247-605bc22ad902?w=800&q=80&fit=crop",
      "https://images.unsplash.com/photo-1727951234414-2c463cc4fd58?w=800&q=80&fit=crop",
      "https://images.unsplash.com/photo-1675026922181-b30935570a78?w=800&q=80&fit=crop",
      "https://images.unsplash.com/photo-1677425900944-be7501c4b04f?w=800&q=80&fit=crop",
    ],
    imageAlts: [
      "Taormina kilátás az Etnára",
      "Etna vulkán",
      "Taormina város",
      "Etna vulkán közeli fotó",
      "Szicíliai tengerpart",
    ],
    fallbackGradient: "from-orange-400 to-red-500",
    fallbackEmoji: "🌋",
    youtubeVideoId: "CPO8v-ePxRE",
  },
  {
    id: "algarve",
    name: "Algarve (Portugália)",
    description:
      "Európa legszebb partszakasza: arany sziklafalak, rejtett barlangok és végtelen strandok. A szörfösök és napimádók paradicsoma.",
    highlights: [
      "Arany sziklafalak",
      "Benagil-barlang",
      "Szörfözés",
      "Olcsó luxus",
    ],
    pros: [
      "Benagil-barlang: a világ egyik legikonikusabb természeti csodája",
      "Arany sziklafalak és türkiz víz — egyedülálló tájkép Európában",
      "Kiváló ár-érték arány: olcsóbb, mint Spanyolország vagy Olaszország",
      "Friss tenger gyümölcsei és pasteis de nata: gasztronómiai élvezet",
    ],
    bestFor:
      "Aki lélegzetelállító sziklás partvidéket és strandot akar, európai áron. A legjobb ár-érték arány Nyugat-Európában.",
    programs: [
      "🏖️ Praia da Marinha (Európa TOP 3 strandja)",
      "🕳️ Benagil-barlang kajakolás / SUP",
      "🏄 Szörfözés Sagres-ben (Európa szörf-fővárosa)",
      "🚤 Hajókirándulás a sziklafalak mentén + delfinlesés",
      "🏘️ Lagos óváros felfedezése és tapas-est",
      "🍤 Friss grillezett hal és cataplana vacsora",
      "⛳ Golfozás világszínvonalú pályákon",
      "🌅 Cabo de São Vicente — Európa legnyugatibb pontja",
    ],
    comparison:
      "A görög szigeteknél és Mallorcánál vadregényesebb partvidék (sziklafalak!). Olcsóbb, mint Szardínia, és a Benagil-barlang egyedülálló. Kicsit hűvösebb a víz, mint a Mediterráneumban.",
    travelTime: "~4 óra (1 átszállással)",
    costCategory: "€€",
    imageUrls: [
      "https://images.unsplash.com/photo-1513341186776-ce8fcdefb51b?w=800&q=80&fit=crop",
      "https://images.unsplash.com/premium_photo-1681578990806-c0f5dd8984bd?w=800&q=80&fit=crop",
      "https://images.unsplash.com/premium_photo-1664111294669-ee1624ed05f6?w=800&q=80&fit=crop",
      "https://images.unsplash.com/photo-1651237079606-d580f710c8b8?w=800&q=80&fit=crop",
      "https://images.unsplash.com/photo-1560242374-7befcc667b39?w=800&q=80&fit=crop",
    ],
    imageAlts: [
      "Algarve arany sziklafalak",
      "Benagil-barlang belülről",
      "Lagos tengerparti sziklák",
      "Praia da Marinha strand",
      "Algarve naplemente sziklákon",
    ],
    fallbackGradient: "from-amber-400 to-yellow-600",
    fallbackEmoji: "🇵🇹",
    youtubeVideoId: "d6L88EoA34o",
  },
  {
    id: "montenegro",
    name: "Montenegró (Kotor)",
    description:
      "Az Adria rejtett kincse: fjordszerű Kotor-öböl, középkori óváros és olcsó mediterrán nyaralás. Horvátország szomszédja, de fele áron.",
    highlights: [
      "Kotor-öböl (fjord)",
      "Középkori óváros",
      "Budva strandok",
      "Olcsó Adria",
    ],
    pros: [
      "Kotor-öböl: Európa egyetlen fjordszerű öble a Mediterráneumban",
      "Középkori óváros (UNESCO) — kisebb és hangulatosabb, mint Dubrovnik",
      "Fele annyiba kerül, mint Horvátország — az Adria legjobb ár-értéke",
      "Autóval elérhető: Budapest → Montenegró ~9 óra",
    ],
    bestFor:
      "Aki adriai nyaralást akar olcsón, lenyűgöző természettel és középkori hangulattal. A 'titkos Horvátország'.",
    programs: [
      "🏰 Kotor óváros felfedezése (UNESCO!)",
      "⛰️ San Giovanni erőd túra (1350 lépcső — de a kilátás!)",
      "🚤 Hajókirándulás a Kotor-öbölben",
      "🏖️ Budva Riviera strandok és éjszakai élet",
      "🏝️ Sveti Stefan: a legikonikusabb adriai sziget-szálloda",
      "🍽️ Montenegrói vacsora: njeguški pršut, ćevapi, vranac bor",
      "🏊 Perast falu és Gospa od Škrpjela (mesterséges sziget)",
      "🚗 Durmitor Nemzeti Park napi kirándulás (hegyi táj!)",
    ],
    comparison:
      "Dubrovnikhoz hasonló élmény, de sokkal olcsóbb és kevésbé zsúfolt. A Kotor-öböl lenyűgözőbb, mint bármi Horvátországban. Strandok gyengébbek, mint a görög szigetek, de a természet és az óváros kárpótol.",
    travelTime: "~9 óra autóval / ~2 óra repülővel (átszállással)",
    costCategory: "€",
    imageUrls: [
      "https://images.unsplash.com/premium_photo-1697730258984-1f4367729b0e?w=800&q=80&fit=crop",
      "https://images.unsplash.com/premium_photo-1697730104948-43575659bf0a?w=800&q=80&fit=crop",
      "https://images.unsplash.com/premium_photo-1697729942579-93186371254e?w=800&q=80&fit=crop",
      "https://images.unsplash.com/photo-1698785822764-899044655784?w=800&q=80&fit=crop",
      "https://images.unsplash.com/photo-1736786723066-40b171486a12?w=800&q=80&fit=crop",
    ],
    imageAlts: [
      "Kotor-öböl felülről",
      "Budva tengerpart",
      "Perast falu és öböl",
      "Kotor középkori óváros",
      "Budva Riviera",
    ],
    fallbackGradient: "from-slate-400 to-blue-600",
    fallbackEmoji: "🏔️",
    youtubeVideoId: "gZlSzpDiPlA",
  },
  {
    id: "korzika",
    name: "Korzika (Franciaország)",
    description:
      "A Szépség Szigete — hegyek és tenger találkozása. Vad sziklás öblök, francia gasztronómia és Napóleon szülőföldje. A Földközi-tenger legváltozatosabb szigete.",
    highlights: [
      "Vad sziklás öblök",
      "Francia gasztronómia",
      "GR20 túraútvonal",
      "Napóleon szülőhelye",
    ],
    pros: [
      "Európa legszebb sziklás öblei: Palombaggia, Santa Giulia, Rondinara",
      "Hegyek a tengerparton — lenyűgöző táj, amit máshol nem látsz",
      "Francia gasztronómia: sajtkülönlegességek, charcuterie, rosé bor",
      "Kevésbé turisztikus, mint Szardínia — autentikusabb élmény",
    ],
    bestFor:
      "Aki vadregényes természetet, francia konyhát és csendes öblöket akar. Autóval járható, rugalmas nyaralás.",
    programs: [
      "🏖️ Palombaggia és Santa Giulia strandok (TOP 5 Európában!)",
      "🏔️ GR20 részlet-túra (a világ legszebb túraútvonala)",
      "🏘️ Bonifacio: sziklaszirten álló város (lélegzetelállító!)",
      "⛵ Scandola természetvédelmi terület hajókirándulás (UNESCO!)",
      "🍷 Korzikai bor- és sajtkóstoló",
      "🏛️ Ajaccio: Napóleon szülővárosa",
      "🤿 Snorkelezés a Lavezzi-szigeteknél",
      "🚗 Szerpentin autóút a Bavella-hágón",
    ],
    comparison:
      "Szardíniához hasonló szigetélmény, de vadabb és kevésbé turistás. A francia konyha más élmény, mint az olasz. Drágább, mint a görög szigetek, de a természet páratlan.",
    travelTime: "~3-4 óra (1 átszállással)",
    costCategory: "€€-€€€",
    imageUrls: [
      "https://images.unsplash.com/premium_photo-1738935671732-cd857eb08d48?w=800&q=80&fit=crop",
      "https://images.unsplash.com/photo-1744271688397-b3a107c7719c?w=800&q=80&fit=crop",
      "https://images.unsplash.com/photo-1653768370917-3490cc41646a?w=800&q=80&fit=crop",
      "https://images.unsplash.com/premium_photo-1764437207352-0764659f960a?w=800&q=80&fit=crop",
      "https://images.unsplash.com/photo-1687469044048-d920c7c1bc04?w=800&q=80&fit=crop",
    ],
    imageAlts: [
      "Bonifacio sziklaszirten álló város",
      "Palombaggia strand türkiz víz",
      "Korzika sziklás öblök",
      "Porto öböl naplemente",
      "Bonifacio kikötő",
    ],
    fallbackGradient: "from-teal-400 to-emerald-600",
    fallbackEmoji: "🏔️",
    youtubeVideoId: "Rx7VBDrGyDQ",
  },
  {
    id: "madeira",
    name: "Madeira (Portugália)",
    description:
      "Az Atlanti-óceán örökzöld gyöngyszeme: drámai sziklák, szubtrópusi növényzet, levada-túrák és egyedülálló természeti élmény. Egész évben kellemes klíma.",
    highlights: [
      "Levada-túrák",
      "Drámai sziklák",
      "Örökzöld növényzet",
      "Egész éves napfény",
    ],
    pros: [
      "Levada-túrák: egyedülálló vízi csatornák mentén séta a dzsungelben",
      "Nyáron tökéletes 22-26°C — nem túl meleg, nem túl hideg",
      "Drámai hegyi táj: sziklaszirtek, vízesések, babérerdők (UNESCO)",
      "Funchal: bájos főváros piaccal, borral és kávéval",
    ],
    bestFor:
      "Aki aktív nyaralást, túrázást és lenyűgöző természetet akar strandolás helyett. A természetjárók álma.",
    programs: [
      "🥾 Levada-túrák (25 Fontes, Caldeirão Verde — vízesésekhez!)",
      "⛰️ Pico do Arieiro → Pico Ruivo túra (a felhők felett!)",
      "🏘️ Funchal óváros, Mercado dos Lavradores piac",
      "🍷 Madeira borkóstoló (200 éves hagyomány!)",
      "🚡 Monte tobogán szánkó (fa szánkón az utcán!)",
      "🐬 Delfin- és bálnales hajókirándulás",
      "🌺 Botanikus kert — szubtrópusi növények paradicsoma",
      "🏖️ Porto Moniz természetes vukanikus medencék",
    ],
    comparison:
      "Teljesen más, mint a strandnyaralás célpontok — ez természet és túrázás. Az Algarve-hoz képest hűvösebb, de a táj sokkal drámaibb. A hegyi élmények páratlanok Európában.",
    travelTime: "~5 óra (1 átszállással)",
    costCategory: "€€",
    imageUrls: [
      "https://images.unsplash.com/photo-1689420748565-a3a151b78c30?w=800&q=80&fit=crop",
      "https://images.unsplash.com/premium_photo-1697730171118-7ee56ca6e21c?w=800&q=80&fit=crop",
      "https://images.unsplash.com/premium_photo-1675526112779-9181f2559894?w=800&q=80&fit=crop",
      "https://images.unsplash.com/photo-1535502841082-b76eedcb990a?w=800&q=80&fit=crop",
      "https://images.unsplash.com/photo-1733254730362-d26994a22cd6?w=800&q=80&fit=crop",
    ],
    imageAlts: [
      "Levada-túra trópusi növényzet",
      "Funchal város felülről",
      "Pico do Arieiro felhők felett",
      "Madeira drámai szikla és óceán",
      "Funchal kikötő",
    ],
    fallbackGradient: "from-green-500 to-emerald-700",
    fallbackEmoji: "🌿",
    youtubeVideoId: "Y29s7aPfKeY",
  },
];
